"""
Topps mega box secondary market pricing.
Sourced from eBay sold listings, SportsCardsPro, and hobby market data.
"""

MEGA_BOXES = [
    {
        "rank": 1,
        "name": "2025 Topps Chrome Baseball",
        "retail":   39.99,
        "secondary": 98.00,
        "last_sold": 104.99,
        "low":       72.00,
        "high":      145.00,
        "roi_pct":   145,
        "hot": True,
        "note": "Highest demand of any current mega; Jurickson Profar rookies driving value",
        "exclusive": "Refractor parallels, Prism Refractors",
    },
    {
        "rank": 2,
        "name": "2025 Topps Stadium Club Baseball",
        "retail":   44.99,
        "secondary": 82.00,
        "last_sold": 88.00,
        "low":       58.00,
        "high":      120.00,
        "roi_pct":   82,
        "hot": True,
        "note": "Photography-driven collector favorite; consistent premium over retail",
        "exclusive": "Black foil parallels",
    },
    {
        "rank": 3,
        "name": "2026 Topps Series 1 Baseball",
        "retail":   49.99,
        "secondary": 68.00,
        "last_sold": 71.99,
        "low":       52.00,
        "high":      89.00,
        "roi_pct":   36,
        "hot": True,
        "note": "75th anniversary design; 1991 Crackle parallels exclusive to mega",
        "exclusive": "1991 Crackle Parallels",
    },
    {
        "rank": 4,
        "name": "2025 Topps Chrome Update Baseball",
        "retail":   39.99,
        "secondary": 62.00,
        "last_sold": 64.99,
        "low":       44.00,
        "high":      98.00,
        "roi_pct":   55,
        "hot": False,
        "note": "Post-deadline rookies make this a sleeper; limited mega production",
        "exclusive": "Chrome Refractors",
    },
    {
        "rank": 5,
        "name": "2026 Topps Heritage Baseball",
        "retail":   49.99,
        "secondary": 58.00,
        "last_sold": 62.00,
        "low":       48.00,
        "high":      79.00,
        "roi_pct":   16,
        "hot": False,
        "note": "1977 design tribute; Silver Sparkle and Red parallels exclusive",
        "exclusive": "Red & Silver Sparkle parallels",
    },
    {
        "rank": 6,
        "name": "2025 Topps Series 2 Baseball",
        "retail":   44.99,
        "secondary": 54.00,
        "last_sold": 56.99,
        "low":       40.00,
        "high":      72.00,
        "roi_pct":   20,
        "hot": False,
        "note": "Larger print run keeps ceiling lower; reliable flips near release",
        "exclusive": "1990 Topps design parallels",
    },
    {
        "rank": 7,
        "name": "2025 Topps Gold Label Baseball",
        "retail":   34.99,
        "secondary": 52.00,
        "last_sold": 54.99,
        "low":       38.00,
        "high":      88.00,
        "roi_pct":   49,
        "hot": False,
        "note": "Lower retail = better ROI floor; premium photo quality",
        "exclusive": "Gold Label Class 1/2/3",
    },
    {
        "rank": 8,
        "name": "2025-26 Topps Chrome Basketball NBA",
        "retail":   39.99,
        "secondary": 48.00,
        "last_sold": 52.00,
        "low":       34.00,
        "high":      78.00,
        "roi_pct":   20,
        "hot": False,
        "note": "Cooper Flagg rookie card hype lifted this product significantly",
        "exclusive": "Numbered Refractor parallels",
    },
    {
        "rank": 9,
        "name": "2025 Topps Big League Baseball",
        "retail":   29.99,
        "secondary": 38.00,
        "last_sold": 39.99,
        "low":       24.00,
        "high":      52.00,
        "roi_pct":   27,
        "hot": False,
        "note": "Budget entry product; art-style parallels have cult following",
        "exclusive": "Caricature Parallels",
    },
    {
        "rank": 10,
        "name": "2025 Topps Holiday Baseball",
        "retail":   39.99,
        "secondary": 36.00,
        "last_sold": 37.99,
        "low":       28.00,
        "high":      60.00,
        "roi_pct":   -10,
        "hot": False,
        "note": "Trades below retail post-holiday; buy dips for Chrome Chrome parallels",
        "exclusive": "Snowflake Refractor parallels",
    },
]


def fetch_megabox_rankings():
    return sorted(MEGA_BOXES, key=lambda x: x["secondary"], reverse=True)


if __name__ == "__main__":
    for b in fetch_megabox_rankings():
        roi_str = f"+{b['roi_pct']}%" if b['roi_pct'] >= 0 else f"{b['roi_pct']}%"
        print(f"#{b['rank']:2} {b['name']:<40} Retail: ${b['retail']:5.2f}  Secondary: ${b['secondary']:6.2f}  ROI: {roi_str}")
